const tileData = [
  {
    img:"https://placeimg.com/400/400/people",
    title:"People"
  },
  {
    img:"https://placeimg.com/400/400/animals",
    title:"animals"
  },
  {
    img:"https://placeimg.com/400/400/nature",
    title:"nature"
  },
  {
    img:"https://placeimg.com/400/400/arch",
    title:"arch"
  },
  {
    img:"https://placeimg.com/400/400/tech",
    title:"tech"
  },
  {
    img:"https://placeimg.com/400/400/people",
    title:"People"
  },
  {
    img:"https://placeimg.com/400/400/animals",
    title:"animals"
  },
  {
    img:"https://placeimg.com/400/400/nature",
    title:"nature"
  },
  {
    img:"https://placeimg.com/400/400/arch",
    title:"arch"
  },
  {
    img:"https://placeimg.com/400/400/tech",
    title:"tech"
  },
  {
    img:"https://placeimg.com/400/400/people",
    title:"People"
  },
  {
    img:"https://placeimg.com/400/400/animals",
    title:"animals"
  },
  {
    img:"https://placeimg.com/400/400/nature",
    title:"nature"
  },
  {
    img:"https://placeimg.com/400/400/arch",
    title:"arch"
  }
];

export default tileData;
